### ISSUE TITLE
Inquiry about Required Number of Views Dataset and GPU-Hours

### ISSUE THREAD

**Issue by ShuzhaoXie** [psc0628/NeRF-PRV#1]
Hi Sicong,

Excellent work! I have a couple of questions regarding the experiment and the data:

1. **GPU-Hours Inquiry**: Could you kindly share an estimate of the GPU-hours necessary for generating the **Required Number of Views Dataset**? I am curious about the computational resources required for such an endeavor.

2. **Dataset Request**: Additionally, I am very interested in exploring the dataset. Could you please share it with me? My email address is xiesz99@gmail.com. I assure you that I will use the data responsibly for academic purposes.

Thank you very much for your time and consideration. I appreciate your efforts and look forward to your response.

**Comment by psc0628** [comment]
Hi Shuzhao,

Thank you for your inquiry.

1. GPU-Hours: It took us about two weeks to generate our dataset using a cluster of 16 A100 GPUs.
2. The dataset is available on [Kaggle](https://www.kaggle.com/datasets/sicongpan/prv-dataset-and-trained-network).

**Comment by ShuzhaoXie** [comment]
Got it, thank you!
